services:
  master:
    image: caobaoqi1029/big-data-study:0.3.0
    container_name: master
    hostname: master # TODO: Change this to name-SID-1
    ports:
      - "8088:8088" # Yarn Web UI
      - "8020:8020"

    command: bash -c "
      service ssh restart &&
      tail -f /dev/null"
    networks:
      - hadoop-network
    depends_on:
      - slave1
      - slave2
      - slave3

  slave1:
    image: caobaoqi1029/big-data-study:0.3.0
    container_name: slave1
    hostname: slave1 # TODO: Change this to name-SID-2
    command: bash -c "
      service ssh restart &&
      tail -f /dev/null"
    networks:
      - hadoop-network

  slave2:
    image: caobaoqi1029/big-data-study:0.3.0
    container_name: slave2
    hostname: slave2 # TODO: Change this to name-SID-3
    command: bash -c "
      service ssh restart &&
      tail -f /dev/null"
    networks:
      - hadoop-network

  slave3:
    image: caobaoqi1029/big-data-study:0.3.0
    container_name: slave3
    hostname: slave3 # TODO: Change this to name-SID-4
    command: bash -c "
      service ssh restart &&
      tail -f /dev/null"
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge